name = "S - Circle Trigon Field" 
description = "Triangles arranged in a circle"
knob1 = "Field Size"
knob2 = "Triangle Skew Right"
knob3 = "Triangle Skew Left" 
knob4 = "Color"
released = "March 21 2017"
