name = "S - Triangle Row" 
description = "Row of Triangles change height with amplitude"
knob1 = "Number of Triangles"
knob2 = "Angle"
knob3 = "Y Position" 
knob4 = "Color"
released = "March 21 2017"
