words = [[u"a partir de", u"from, as of"],
[u"a través de", u"through, across"],
[u"a", u"a, to"],
[u"abajo", u"down, below, downstairs"],
[u"abandonar", u"to abandon"],
[u"abrir", u"to open, unlock"],
[u"absoluto/a", u"absolute"],
[u"abuelo", u"grandfathers, grandpa"],
[u"acabar", u"to finish"],
[u"acaso", u"perhaps, maybe"],
[u"acción\ciones", u"action"],
[u"aceptar", u"to accept"],
[u"acercar", u"to approach"],
[u"acompañar", u"to accompany"],
[u"acordar", u"to decide"],
[u"actitud", u"attitude"],
[u"actividad", u"activity"],
[u"acto", u"act"],
[u"actual", u"present"],
[u"actuar", u"to act"],
[u"acudir", u"to go, come"],
[u"acuerdo", u"agreement"],
[u"adelante", u"ahead"],
[u"además de", u"in addition to, besides, furthermore"],
[u"además", u"in addition, besides, furthermore"],
[u"adquirir", u"to acquire"],
[u"advertir", u"to notice, warn"],
[u"afectar", u"to affect"],
[u"afirmar", u"to affirm"],
[u"agua", u"water"],
[u"ahí", u"there"],
[u"ahí", u"there"],
[u"ahora", u"now"],
[u"aire", u"air"],
[u"al", u"to, to the"],
[u"alcanzar", u"to reach"],
[u"alejar", u"to move away, remove"],
[u"alemán/mana", u"german"],
[u"algo", u"something"],
[u"alguien", u"somebody, someone"],
[u"alguien", u"somebody"],
[u"algún", u"some, any"],
[u"alguno/a", u"some, any"],
[u"allá", u"there"],
[u"allí", u"there"],
[u"alma", u"soul"],
[u"alto/a", u"tall, high, stop"],
[u"altura", u"height"],
[u"amar", u"to love"],
[u"ambos/bas", u"both"],
[u"americano/a", u"american"],
[u"amigo/a", u"friend"],
[u"amor", u"love"],
[u"amplio/plia", u"ample"],
[u"añadir", u"to add"],
[u"análisis", u"analysis"],
[u"andar", u"to walk"],
[u"animal", u"animal"],
[u"año", u"year"],
[u"ante", u"before, in front of"],
[u"ante", u"before"],
[u"anterior", u"previous"],
[u"antes de", u"before"],
[u"antiguo/gua", u"ancient, old"],
[u"anunciar", u"to announce"],
[u"aparecer", u"to appear"],
[u"apenas", u"hardly,scarcely"],
[u"aplicar", u"to apply"],
[u"apoyar", u"to support, lean"],
[u"aprender", u"to learn"],
[u"aprovechar", u"to take advantage of"],
[u"aquel", u"that"],
[u"aquello/a", u"that"],
[u"aquí", u"here"],
[u"árbol", u"tree"],
[u"arma", u"weapon"],
[u"arriba", u"up"],
[u"arte", u"art"],
[u"asegurar", u"to assure"],
[u"así como", u"as well as, such, like that"],
[u"así que", u"so, therefore"],
[u"así", u"like this"],
[u"aspecto", u"aspect"],
[u"asunto", u"matter, bussiness"],
[u"atención\ciones", u"attention"],
[u"atrás", u"back, behind"],
[u"atreverse", u"to dare"],
[u"aumentar", u"to increase, raise"],
[u"aun", u"even"],
[u"aún", u"still"],
[u"aunque", u"though, although"],
[u"auténtico/a", u"authentic"],
[u"autor/a", u"author"],
[u"autoridad", u"authority"],
[u"avanzar", u"to advance"],
[u"ayer", u"yesterday"],
[u"ayuda", u"aid, help"],
[u"ayudar", u"to help"],
[u"azul", u"blue"],
[u"bajar", u"to bring down, lower, go down"],
[u"bajo/a", u"low, short, faint"],
[u"barcelona", u"barcelona"],
[u"barrio", u"neighborhood"],
[u"base", u"base, basis"],
[u"bastante", u"fairly, rather"],
[u"bastar", u"to be enough, suffice"],
[u"beber", u"to drink"],
[u"bien", u"well, good"],
[u"blanco/a", u"white"],
[u"boca", u"mouth"],
[u"brazo", u"arm"],
[u"buen", u"good, well"],
[u"buscar", u"to look for, to seek"],
[u"caballo", u"horse"],
[u"caber", u"to fit, go into"],
[u"cabeza", u"head"],
[u"cabo", u"end, stub"],
[u"cada", u"each"],
[u"cadena", u"chain"],
[u"caer", u"to fall"],
[u"calle", u"street"],
[u"cama", u"bed"],
[u"cambiar", u"to change"],
[u"cambio", u"change"],
[u"caminar", u"to walk"],
[u"camino", u"road"],
[u"campaña", u"countryside"],
[u"campo", u"field"],
[u"cantar", u"to sing"],
[u"cantidad", u"quantity"],
[u"capacidad", u"capacity"],
[u"capaz\paces", u"able"],
[u"capital", u"capital"],
[u"cara", u"face"],
[u"carácter/racteres", u"character"],
[u"carne", u"meat"],
[u"carrera", u"running"],
[u"carta", u"letter"],
[u"casa", u"house"],
[u"casar", u"to marry"],
[u"casi", u"almost"],
[u"caso", u"case"],
[u"catalán", u"catalan"],
[u"causa", u"cause, reason"],
[u"celebrar", u"to celebrate"],
[u"célula", u"cell"],
[u"central", u"central"],
[u"centro", u"center, downtown"],
[u"cerebro", u"brain"],
[u"cerrar", u"to close"],
[u"chica", u"small, girl,litlle"],
[u"chico/a", u"boy, girl"],
[u"cielo", u"sky, heaven"],
[u"ciencia", u"science"],
[u"científico/a", u"scientific"],
[u"ciento", u"one hundred"],
[u"cierto/a", u"TRUE"],
[u"cinco", u"five"],
[u"cine", u"cinema, movies"],
[u"circunstancia", u"circumstance"],
[u"ciudad", u"city"],
[u"ciudadano/a", u"citizen"],
[u"civil", u"civil"],
[u"claro/a", u"clearly, clear"],
[u"clase", u"class"],
[u"coche", u"car, automobile, coach, carriage"],
[u"coger", u"to take"],
[u"colocar", u"to place, put"],
[u"color", u"color"],
[u"comentar", u"to comment, discuss, mention"],
[u"comenzar", u"to begin, start"],
[u"comer", u"to eat"],
[u"como", u"as, since, like"],
[u"cómo", u"how"],
[u"compañero/a", u"partner, companion"],
[u"compañía", u"company"],
[u"completo", u"complete, full"],
[u"comprar", u"to buy, purchase"],
[u"comprender", u"to comprehend, to understand"],
[u"comprobar", u"to check"],
[u"común\munes", u"common"],
[u"comunicación\ciones", u"communication"],
[u"con que", u"so long as"],
[u"con", u"with"],
[u"concepto", u"concept"],
[u"conciencia", u"conscience"],
[u"concreto", u"concrete, specific"],
[u"condición\siones", u"condition"],
[u"conducir", u"to drive"],
[u"conjunto", u"joint, outfit, band"],
[u"conocer", u"to know, meet"],
[u"conocimiento", u"knowlogde"],
[u"consecuencia", u"consequence"],
[u"conseguir", u"to obtain"],
[u"conservar", u"to conserve"],
[u"considerar", u"to consider"],
[u"consistir", u"to consist"],
[u"constante", u"constant"],
[u"constituir", u"to constitute"],
[u"construir", u"to construct, build"],
[u"contacto", u"contact"],
[u"contar", u"to count"],
[u"contemplar", u"to contemplate"],
[u"contener", u"to contain"],
[u"contestar", u"to answer, reply"],
[u"continuar", u"to continue"],
[u"contra", u"against"],
[u"contrario", u"opposite"],
[u"control", u"control, check"],
[u"controlar", u"to control"],
[u"convencer", u"to convince"],
[u"conversación", u"conversation"],
[u"convertir", u"to turn into, convert"],
[u"corazón", u"heart"],
[u"correr", u"to run, race"],
[u"corresponder", u"to correspond, belong"],
[u"corriente", u"current"],
[u"cortar", u"to cut"],
[u"cosa", u"thing"],
[u"costumbre", u"custom, habit"],
[u"crear", u"to create"],
[u"crecer", u"to grow, increase"],
[u"creer", u"to believe"],
[u"crisis", u"crisis"],
[u"cruzar", u"to cross"],
[u"cuadro", u"picture, square, painting"],
[u"cual", u"as, like"],
[u"cuál", u"which, what"],
[u"cualquier", u"any"],
[u"cuando", u"when"],
[u"cuanto", u"how much, as"],
[u"cuánto", u"how much"],
[u"cuarto/a", u"quarter"],
[u"cuatro", u"four"],
[u"cubrir", u"to cover"],
[u"cuenta", u"count"],
[u"cuerpo", u"body"],
[u"cuestión", u"matter, affair"],
[u"cultura", u"culture"],
[u"cultural", u"cultural"],
[u"cumplir", u"to accomplish, carry out"],
[u"cuyo/a", u"whose, of whom"],
[u"dar", u"to give"],
[u"dato", u"data"],
[u"de", u"of, from"],
[u"deber", u"to owe"],
[u"decidir", u"to decide"],
[u"decir", u"to say, tell"],
[u"decisión", u"decision"],
[u"declarar", u"to declare"],
[u"dedicar", u"to dedicate"],
[u"dedo", u"finger, toe"],
[u"defender", u"to defend"],
[u"defensa", u"defense"],
[u"definir", u"to define"],
[u"definitivo", u"definitive"],
[u"dejar", u"to leave"],
[u"del", u"of, from"],
[u"demás", u"rest of the"],
[u"demasiado", u"too much"],
[u"democracia", u"democracy"],
[u"demostrar", u"to demonstrate"],
[u"dentro de", u"within, in"],
[u"depender", u"to depend"],
[u"derecha", u"right"],
[u"derecho", u"straight, rigth"],
[u"desaparecer", u"to disappear"],
[u"desarrollar", u"to develop"],
[u"desarrollo", u"development"],
[u"desconocer", u"to not know, fail to recognize"],
[u"descubrir", u"to discover"],
[u"desde que", u"since"],
[u"desde", u"from, since"],
[u"desear", u"to wish"],
[u"deseo", u"desire"],
[u"despertar", u"to wake up"],
[u"después de", u"after"],
[u"después", u"afterwards, then"],
[u"destino", u"destiny, destination"],
[u"detener", u"to stop"],
[u"determinar", u"to determine"],
[u"día", u"day"],
[u"diario/ria", u"newspaper"],
[u"diez", u"ten"],
[u"diferencia", u"difference"],
[u"diferente", u"different"],
[u"difícil", u"difficult"],
[u"dificultad", u"difficulty"],
[u"dinero", u"money"],
[u"dios/diosa", u"god, goddes"],
[u"dirección", u"address, direction"],
[u"directo", u"direct, straight"],
[u"director/tora", u"director, manager"],
[u"dirigir", u"to direct"],
[u"disponer", u"to arrange"],
[u"distancia", u"distance"],
[u"distinto", u"different"],
[u"diverso", u"diverse"],
[u"doble", u"double"],
[u"doctor/tora", u"doctor"],
[u"dolor", u"pain"],
[u"don", u"gift, talent"],
[u"donde", u"where"],
[u"dónde", u"where"],
[u"dormir", u"to sleep"],
[u"dos", u"two"],
[u"duda", u"doubt"],
[u"durante", u"during"],
[u"duro", u"hard"],
[u"e", u"and"],
[u"echar", u"to throw, cast"],
[u"económico", u"economic, economical"],
[u"edad", u"age"],
[u"efecto", u"efect"],
[u"ejemplo", u"example"],
[u"ejército", u"army"],
[u"ejército", u"army"],
[u"el/a", u"the"],
[u"él", u"he, him"],
[u"elección", u"election"],
[u"elegir", u"to choose, select"],
[u"elemento", u"element"],
[u"elevar", u"to elevate, raise"],
[u"empezar", u"to begin, start"],
[u"empresa", u"company"],
[u"en", u"in, into, inside, on"],
[u"encender", u"to light, switch on, set fire to"],
[u"encima", u"on top"],
[u"encontrar", u"to find"],
[u"encuentro", u"encounter, meeting"],
[u"energía", u"energy"],
[u"enfermedad", u"illness, disease, sickness"],
[u"enfermo", u"ill, sick"],
[u"enorme", u"enormous"],
[u"enseñar", u"to teach"],
[u"entender", u"to understand"],
[u"enterar", u"to find out, inform"],
[u"entonces", u"then"],
[u"entrada", u"entrance, entry"],
[u"entrar", u"to enter"],
[u"entre", u"between, among"],
[u"entregar", u"to deliver, give"],
[u"enviar", u"to send"],
[u"época", u"epoch, period"],
[u"equipo", u"equipment, team"],
[u"error", u"error, mistake"],
[u"es decir", u"that is to say"],
[u"escapar", u"to escape, run away"],
[u"escribir", u"to write"],
[u"escritor/tora", u"writer"],
[u"escuchar", u"to listen, heard"],
[u"ese/a", u"that"],
[u"esfuerzo", u"effort, endeavor, exertion"],
[u"eso", u"that"],
[u"espacio", u"space"],
[u"espalda", u"back"],
[u"españa", u"spain"],
[u"español/ñola", u"spanish"],
[u"española", u"Spanish, spaniard"],
[u"especial", u"special"],
[u"especie", u"species"],
[u"esperanza", u"hope, prospect"],
[u"esperar", u"to hope, wait"],
[u"espíritu", u"spirit"],
[u"ésta", u"is"],
[u"establecer", u"to establish"],
[u"estado", u"state"],
[u"estados unidos", u"united States"],
[u"estar", u"to be, stay"],
[u"éste/a", u"this one"],
[u"este/a", u"this"],
[u"este", u"this"],
[u"esto", u"this"],
[u"estrella", u"star"],
[u"estructura", u"structure"],
[u"estudiar", u"to study"],
[u"estudio", u"study, studio"],
[u"etapa", u"stage"],
[u"europa", u"europe"],
[u"europeo/pea", u"european"],
[u"evidente", u"evident"],
[u"evitar", u"to avoid"],
[u"exacto/a", u"exact"],
[u"exigir", u"to demand"],
[u"existencia", u"existence"],
[u"existir", u"to exist"],
[u"éxito", u"success"],
[u"experiencia", u"experience"],
[u"explicar", u"to explain"],
[u"expresión", u"expression"],
[u"extender", u"to extend"],
[u"exterior", u"outside, exterior"],
[u"extranjero/a", u"foreigner, foreign"],
[u"extraño", u"strange, foreign"],
[u"extremo", u"extreme"],
[u"fácil", u"easy"],
[u"falta", u"lack"],
[u"faltar", u"to lack"],
[u"familia", u"family"],
[u"familiar", u"familial, family"],
[u"famoso", u"famous"],
[u"fenómeno", u"phenomenon"],
[u"fiesta", u"celebration, party"],
[u"figura", u"figure, shape"],
[u"figura", u"to figure"],
[u"fijar", u"to faten, affix"],
[u"fin", u"end"],
[u"final", u"end, final"],
[u"físico", u"physical, physicist"],
[u"flor", u"flower"],
[u"fondo", u"bottom, rear"],
[u"forma", u"shape"],
[u"formar", u"to form"],
[u"francés/cesa", u"french"],
[u"francés", u"french"],
[u"francia", u"france"],
[u"frase", u"phrase"],
[u"frecuencia", u"frequency"],
[u"frente", u"in front"],
[u"frío/a", u"cold, cool"],
[u"fuego", u"fire"],
[u"fuente", u"source"],
[u"fuera de", u"outside of, beyond"],
[u"fuerte", u"hard, strong"],
[u"fuerza", u"force, strength"],
[u"función", u"function"],
[u"funcionar", u"to work, run, function"],
[u"fundamental", u"fundamental"],
[u"fútbol", u"soccer, football"],
[u"futuro", u"future"],
[u"ganar", u"to win"],
[u"general", u"general"],
[u"gente", u"people"],
[u"gesto", u"gesture"],
[u"gobierno", u"government"],
[u"golpe", u"blow"],
[u"gracia", u"grace"],
[u"gran", u"big"],
[u"grande", u"big, great"],
[u"grave", u"grave, deep"],
[u"gritar", u"to shout, scream"],
[u"grupo", u"group"],
[u"guardar", u"to keep"],
[u"guerra", u"war"],
[u"gustar", u"to taste, like"],
[u"gusto", u"taste, pleasure, liking"],
[u"haber", u"to have, has"],
[u"habitación", u"room, bedroom"],
[u"habitual", u"habitual, usual"],
[u"hablar", u"to speak, talk"],
[u"hacer", u"to do, make"],
[u"hacia", u"towards"],
[u"hallar", u"to find, discover"],
[u"hasta que", u"until, even"],
[u"hasta", u"until, even"],
[u"hecho/cha", u"fact"],
[u"hermana", u"sister"],
[u"hermano/a", u"brother"],
[u"hermoso/a", u"beautiful"],
[u"hija", u"daughter"],
[u"hijo/a", u"son, daughter"],
[u"historia", u"history"],
[u"histórico", u"historical"],
[u"hombre", u"man"],
[u"hombro", u"shoulder"],
[u"hora", u"hour"],
[u"hoy", u"today"],
[u"humano/a", u"human"],
[u"idea", u"idea"],
[u"iglesia", u"church"],
[u"igual", u"equal"],
[u"imagen\imágenes", u"image"],
[u"imaginar", u"to imagine"],
[u"impedir", u"to prevent"],
[u"imponer", u"to impose, command"],
[u"importancia", u"importance"],
[u"importante", u"important"],
[u"importar", u"to matter, be important"],
[u"imposible", u"impossible"],
[u"incluir", u"to include"],
[u"incluso", u"even, in fact"],
[u"indicar", u"to indicate"],
[u"individuo", u"individual"],
[u"información\ciones", u"information"],
[u"informar", u"to inform"],
[u"informar", u"to inform"],
[u"inglés/glesa", u"english"],
[u"iniciar", u"to initiate"],
[u"inmediato/a", u"immediate"],
[u"insistir", u"to insist"],
[u"instante", u"moment, instant"],
[u"intentar", u"to try"],
[u"interés\reses", u"interest"],
[u"interesar", u"to interest"],
[u"interior", u"interior, inner"],
[u"internacional", u"international"],
[u"introducir", u"to introduce, insert"],
[u"ir", u"to go"],
[u"izquierda", u"left"],
[u"jamás", u"never"],
[u"jefe/a", u"chief, leader, boss"],
[u"joven", u"young person"],
[u"juego", u"game, playing"],
[u"jugador", u"player, gambler"],
[u"jugar", u"to play, gambler"],
[u"juicio", u"judgment, sense"],
[u"junto a", u"next to"],
[u"junto", u"together, joined, close"],
[u"justo", u"just, fair"],
[u"labio", u"lip"],
[u"lado", u"side"],
[u"lanzar", u"to throw"],
[u"largo", u"long"],
[u"lector/tora", u"reader"],
[u"leer", u"to read"],
[u"lengua", u"language, tongue"],
[u"lenguaje", u"language"],
[u"lento", u"slow"],
[u"levantar", u"to lift, raise"],
[u"ley", u"law"],
[u"libertad", u"freedom"],
[u"libre", u"free"],
[u"libro", u"book"],
[u"limitar", u"to limit"],
[u"línea", u"line"],
[u"literatura", u"literature"],
[u"llamar", u"to call, phone"],
[u"llegar", u"to arrive, come"],
[u"llenar", u"to fill"],
[u"lleno", u"full"],
[u"llevar", u"to take, carry"],
[u"llorar", u"to cry, weep"],
[u"lo", u"the for it"],
[u"loco/a", u"crazy, insane"],
[u"lograr", u"to obtain, achieve, get"],
[u"lucha", u"fight, struggle"],
[u"luego", u"then, later"],
[u"lugar", u"place"],
[u"luz", u"light, lighting"],
[u"madre", u"mother"],
[u"mal", u"badly, poorly, incorrectly"],
[u"malo/a", u"bad"],
[u"mañana", u"tomorrow"],
[u"mandar", u"to command"],
[u"manera", u"way, manner"],
[u"manifestar", u"to declare"],
[u"mano", u"hand"],
[u"mantener", u"to maintain"],
[u"máquina", u"machine"],
[u"mar", u"sea"],
[u"marcar", u"to mark"],
[u"marcha", u"march"],
[u"marchar", u"to march"],
[u"marido", u"husband"],
[u"mas", u"but"],
[u"más", u"more"],
[u"masa", u"mass"],
[u"matar", u"to kill"],
[u"materia", u"matter"],
[u"material", u"material"],
[u"máximo", u"maximum"],
[u"mayor", u"greater"],
[u"mayoría", u"majority"],
[u"mediante", u"by means of"],
[u"médico/a", u"doctor"],
[u"medida", u"measurement"],
[u"medio/dia", u"means"],
[u"mejor", u"better"],
[u"memoria", u"memory"],
[u"menor", u"minor"],
[u"menos", u"less"],
[u"menudo", u"small, insignificant"],
[u"mercado", u"market"],
[u"merecer", u"to deserve"],
[u"mes", u"month"],
[u"mesa", u"it pulls"],
[u"meter", u"to put"],
[u"método", u"method"],
[u"metro", u"meter"],
[u"mi\mis", u"my, not me"],
[u"mí", u"me, not my"],
[u"miedo", u"fear"],
[u"miembro", u"member"],
[u"mientras que", u"whereas, while"],
[u"mientras", u"while"],
[u"mil", u"thousand"],
[u"militar", u"military man"],
[u"millón", u"million"],
[u"mínimo/a", u"minimum"],
[u"ministro/tra", u"minister"],
[u"minuto", u"minute"],
[u"mío/a", u"mine"],
[u"mirada", u"watched"],
[u"mirar", u"to watch"],
[u"mismo", u"same"],
[u"mitad", u"half"],
[u"modelo", u"model"],
[u"moderno/a", u"modern"],
[u"modo", u"way, manner, mode"],
[u"momento", u"moment"],
[u"moral", u"moral"],
[u"morir", u"to die"],
[u"mostrar", u"to show"],
[u"motivo", u"reason"],
[u"mover", u"to move, stir"],
[u"movimiento", u"movement, motion"],
[u"muchacho/cha", u"boy"],
[u"mucho", u"much"],
[u"muerte", u"death"],
[u"mujer/jeres", u"woman, women"],
[u"mundial", u"worldwide"],
[u"mundo", u"world"],
[u"música", u"music"],
[u"muy", u"very, highly"],
[u"nacer", u"to be born"],
[u"nacional", u"national"],
[u"nada", u"nothing"],
[u"nadie", u"nobody, no-one"],
[u"natural", u"natural"],
[u"naturaleza", u"nature"],
[u"necesario/ria", u"necessary"],
[u"necesidad", u"necessity,need"],
[u"necesitar", u"to need"],
[u"negar", u"to deny"],
[u"negocio", u"business"],
[u"negro/gra", u"black"],
[u"ni siquiera", u"not even"],
[u"ni", u"nor, neither"],
[u"niña", u"girl, child"],
[u"ningún", u"none"],
[u"ninguno/a", u"no, none, nobody, no one"],
[u"niño/a", u"boy, girl"],
[u"nivel", u"level"],
[u"no", u"no"],
[u"noche", u"night"],
[u"nombre", u"name"],
[u"normal", u"normal"],
[u"norteamericano/a", u"North American"],
[u"notar", u"to notice"],
[u"noticia", u"the news"],
[u"novela", u"novel"],
[u"nuestro/tra", u"ours"],
[u"nuevo/a", u"new"],
[u"número", u"number"],
[u"nunca", u"never"],
[u"o", u"or"],
[u"objetivo", u"objective"],
[u"objeto", u"object"],
[u"obligar", u"to force, oblige"],
[u"obra", u"work"],
[u"observar", u"to observe"],
[u"obtener", u"to obtain, get"],
[u"ocasión\siones", u"occasion"],
[u"ocho", u"eight"],
[u"ocupar", u"to occupy"],
[u"ocurrir", u"to happen"],
[u"oficial", u"official"],
[u"ofrecer", u"to offer"],
[u"oír", u"to hear"],
[u"ojo", u"eye"],
[u"olvidar", u"to forget"],
[u"operación", u"operation"],
[u"opinión", u"opinion"],
[u"origen/rígenes", u"origin"],
[u"oro", u"gold"],
[u"oscuro/a", u"dark, obscure"],
[u"otro/tra", u"another, other"],
[u"paciente", u"patient"],
[u"padre", u"father"],
[u"pagar", u"to pay"],
[u"página", u"page"],
[u"país", u"country, nation"],
[u"países", u"countries"],
[u"palabra", u"word"],
[u"papel", u"paper"],
[u"par", u"pair, couple"],
[u"para que", u"so that"],
[u"para", u"for, towars, stop"],
[u"parar", u"to stop, stand"],
[u"parecer", u"to seem"],
[u"pared", u"wall"],
[u"pareja", u"even, couple, pair"],
[u"parte", u"part"],
[u"participar", u"to participate"],
[u"particular", u"particular, private"],
[u"partido", u"party, game"],
[u"partir", u"to start off, depart, slipt, divide"],
[u"pasado", u"past"],
[u"pasar", u"to happen, pass"],
[u"paso", u"step"],
[u"paso", u"step"],
[u"paz", u"peace"],
[u"pecho", u"chest"],
[u"pedir", u"to request, ask for"],
[u"película", u"film, movie"],
[u"peligro", u"danger"],
[u"pelo", u"hair"],
[u"pena", u"pain, penalty"],
[u"pensamiento", u"though"],
[u"pensar", u"to think"],
[u"peor", u"worse"],
[u"pequeño/a", u"small"],
[u"perder", u"to lose, miss"],
[u"perfecto", u"perfect"],
[u"periódico/a", u"newspaper"],
[u"periodista", u"journalist"],
[u"permanecer", u"to remain"],
[u"permitir", u"to allow"],
[u"pero", u"but"],
[u"perro/rra", u"dog"],
[u"persona", u"person"],
[u"personaje", u"person"],
[u"personal", u"personal"],
[u"pertenecer", u"to belong to"],
[u"pesar", u"to weigh"],
[u"peso", u"weight"],
[u"pie", u"foot"],
[u"piedra", u"stone"],
[u"piel", u"skin"],
[u"pierna", u"leg"],
[u"piso", u"floor"],
[u"placer", u"to please"],
[u"plan", u"plan"],
[u"plantear", u"to expound, raise"],
[u"plaza", u"seat, square"],
[u"pleno", u"full, complete"],
[u"población\ciones", u"population"],
[u"pobre", u"poor"],
[u"poco/a", u"little, few"],
[u"poder", u"to be able to, can, might, may"],
[u"policía", u"police"],
[u"política", u"politics"],
[u"político", u"political"],
[u"poner", u"to put"],
[u"por ejemplo", u"for example"],
[u"por", u"by, for, per"],
[u"porque", u"because, why"],
[u"poseer", u"to posses, own"],
[u"posibilidad", u"possibility"],
[u"posible", u"posible"],
[u"posición\ciones", u"position"],
[u"práctico", u"practical"],
[u"precio", u"price, cost"],
[u"preciso/a", u"precise"],
[u"preferir", u"to prefer"],
[u"pregunta", u"a question"],
[u"preguntar", u"to ask"],
[u"prensa", u"press"],
[u"preocupar", u"to worry"],
[u"preparar", u"to prepare"],
[u"presencia", u"presence"],
[u"presentar", u"to present"],
[u"presente", u"present"],
[u"presidente", u"president"],
[u"pretender", u"to try, court"],
[u"primer", u"first"],
[u"primero/a", u"first"],
[u"principal", u"principal"],
[u"principio", u"beginning, principle"],
[u"privar", u"deprive"],
[u"probable", u"probable"],
[u"problema", u"problem"],
[u"proceso", u"process"],
[u"producir", u"to produce"],
[u"producto", u"product"],
[u"profesional", u"professional"],
[u"profesor/sora", u"professor, teacher"],
[u"profundo/a", u"deep"],
[u"programa", u"program"],
[u"pronto/a", u"soon, quick, prompt"],
[u"propio/pia", u"own"],
[u"proponer", u"to propose, nominate"],
[u"provocar", u"to cause"],
[u"próximo/a", u"next"],
[u"proyecto", u"project"],
[u"prueba", u"test, proof, evidence"],
[u"publicar", u"to publish"],
[u"público/a", u"public"],
[u"pueblo", u"town"],
[u"pueblo", u"town"],
[u"puerta", u"door"],
[u"pues", u"then, since, because"],
[u"puesto", u"position, place"],
[u"punto", u"point"],
[u"puro/a", u"pure"],
[u"que", u"that"],
[u"qué", u"what"],
[u"quedar", u"to stay"],
[u"querer", u"to want"],
[u"quien", u"who"],
[u"quién", u"who"],
[u"quitar", u"to remove, take away"],
[u"quizá", u"perhaps, maybe"],
[u"radio", u"radio"],
[u"rápido/a", u"rapid, quick"],
[u"rato", u"short while"],
[u"razón\zones", u"reason"],
[u"real", u"royal, real"],
[u"realidad", u"reality"],
[u"realizar", u"to make, realize"],
[u"recibir", u"to receive"],
[u"reciente", u"recent"],
[u"recoger", u"to gather, pick up"],
[u"reconocer", u"to recognize"],
[u"recordar", u"to remember, remind"],
[u"recorrer", u"to cross, travel through"],
[u"recuerdo", u"memory, remembrance"],
[u"recuperar", u"to recover"],
[u"reducir", u"to reduce"],
[u"referir", u"to refer"],
[u"régimen", u"regime"],
[u"regresar", u"to return, come back"],
[u"reír", u"to laugh"],
[u"relación\ciones", u"relation"],
[u"religioso/a", u"religious"],
[u"repetir", u"to repeat"],
[u"representar", u"to represent"],
[u"resolver", u"to solve"],
[u"responder", u"to answer"],
[u"responsable", u"responsible"],
[u"respuesta", u"answer"],
[u"resto", u"rest"],
[u"resultado", u"result, outcome"],
[u"resultar", u"to turn out, work out, succeed"],
[u"reunión\niones", u"meeting"],
[u"reunir", u"to unite, join"],
[u"revista", u"magazine"],
[u"rey", u"king"],
[u"rico/a", u"rich"],
[u"riesgo", u"risk"],
[u"río", u"river"],
[u"rodear", u"to surround, encircle"],
[u"rojo/a", u"red"],
[u"romper", u"to break"],
[u"ropa", u"clothes"],
[u"rostro", u"face"],
[u"saber", u"to know"],
[u"sacar", u"to remove, take out"],
[u"sala", u"room, living room"],
[u"salida", u"exit, departure"],
[u"salir", u"to leave, go out"],
[u"sangre", u"blood"],
[u"secreto/a", u"secret"],
[u"sector", u"sector"],
[u"seguir", u"to follow"],
[u"según", u"according to"],
[u"segundo", u"second"],
[u"seguridad", u"security"],
[u"seguro/a", u"safe"],
[u"seis", u"six"],
[u"semana", u"week"],
[u"semejante", u"similar"],
[u"señalar", u"to indicate, point out"],
[u"señor/ñora", u"sir/madam"],
[u"sensación\ciones", u"sensation, feeling"],
[u"sentar", u"to seat, sit"],
[u"sentido/a", u"heartfelt,sense"],
[u"sentimiento", u"feeling"],
[u"sentimiento", u"feeling"],
[u"sentir", u"to feel"],
[u"separar", u"to separate"],
[u"ser", u"to be"],
[u"serie/ria", u"series"],
[u"serio", u"serious"],
[u"servicio", u"service"],
[u"servir", u"to serve"],
[u"sexo", u"sex"],
[u"sexual", u"sexual"],
[u"si", u"if, yes"],
[u"sí", u"yes"],
[u"sido", u"been"],
[u"siempre", u"always"],
[u"siete", u"seven"],
[u"siglo", u"century"],
[u"significar", u"to mean"],
[u"siguiente", u"following, next"],
[u"silencio", u"silence"],
[u"simple", u"simple"],
[u"sin", u"without"],
[u"sino que", u"but that"],
[u"sino", u"but, rather"],
[u"sistema", u"system"],
[u"sitio", u"place, site"],
[u"situación\ciones", u"situation"],
[u"situar", u"to locate"],
[u"sobre", u"envelope, on"],
[u"social", u"social"],
[u"socialista", u"socialist"],
[u"sociedad", u"society"],
[u"sol", u"sun"],
[u"solo/a", u"alone"],
[u"sólo", u"only"],
[u"solución\ciones", u"solution"],
[u"sombra", u"shadow"],
[u"someter", u"to subjugate"],
[u"sonar", u"to sound"],
[u"sonreír", u"to smile"],
[u"sonrisa", u"smile"],
[u"sorprender", u"to surprise"],
[u"sostener", u"to maintain, support, hold"],
[u"su", u"his"],
[u"subir", u"to raise"],
[u"suceder", u"to happen/ occur"],
[u"suelo", u"ground, floor"],
[u"sueño", u"dream"],
[u"suerte", u"luck"],
[u"suficiente", u"enough"],
[u"sufrir", u"to suffer"],
[u"superar", u"to surpass"],
[u"superior", u"superior"],
[u"suponer", u"to suppose"],
[u"surgir", u"to arise"],
[u"suyo/a", u"his/her/its"],
[u"tal vez", u"perhaps"],
[u"tal", u"so"],
[u"también", u"also, too"],
[u"tampoco", u"neither"],
[u"tan", u"so"],
[u"tanto/a", u"so much"],
[u"tarde", u"late"],
[u"tarea", u"homewrok"],
[u"técnica", u"technique"],
[u"técnico/a", u"technician"],
[u"televisión\siones", u"television"],
[u"tema", u"theme"],
[u"temer", u"to fear"],
[u"tender", u"to strech out"],
[u"tener", u"to have"],
[u"teoría", u"theory"],
[u"tercer", u"third"],
[u"terminar", u"to finish"],
[u"término", u"term"],
[u"texto", u"text"],
[u"tía", u"aunt"],
[u"tiempo", u"time"],
[u"tierra", u"earth"],
[u"tío/tía", u"uncle / aunt"],
[u"tipo/a", u"guy"],
[u"tirar", u"to throw"],
[u"título", u"title"],
[u"tocar", u"to touch"],
[u"todavía", u"still"],
[u"todo/a", u"everything"],
[u"tomar", u"to take, to drink"],
[u"tono", u"tone"],
[u"total", u"total"],
[u"trabajar", u"to work"],
[u"trabajo", u"job"],
[u"traer", u"to bring"],
[u"tras", u"after"],
[u"tratar", u"to try"],
[u"tres", u"three"],
[u"tu", u"your, you"],
[u"último/a", u"last"],
[u"un/una", u"a, an"],
[u"único/a", u"only"],
[u"único", u"only, unique"],
[u"unidad", u"unit"],
[u"unir", u"to unite"],
[u"uno/una", u"one"],
[u"usar", u"to use"],
[u"uso", u"use"],
[u"usted", u"you"],
[u"utilizar", u"to use"],
[u"vacío/cía", u"empty"],
[u"valer", u"to be worth"],
[u"valor", u"value"],
[u"varias", u"several"],
[u"varios", u"several"],
[u"vecino/a", u"neighbor"],
[u"veinte", u"twenty"],
[u"velocidad", u"speed"],
[u"vender", u"to sell"],
[u"venir", u"to come"],
[u"ventana", u"window"],
[u"ver", u"to see"],
[u"verano", u"summer"],
[u"verdad", u"truth"],
[u"verdadero/a", u"TRUE"],
[u"verde", u"green"],
[u"vestir", u"to dress"],
[u"vez\veces", u"time"],
[u"viaje", u"travel"],
[u"vida", u"life"],
[u"viejo/a", u"old"],
[u"viento", u"wind"],
[u"violencia", u"violence"],
[u"vista", u"vision"],
[u"vivir", u"to live"],
[u"vivo/a", u"alive"],
[u"voluntad", u"will"],
[u"volver", u"to return"],
[u"voz\voces", u"voice"],
[u"vuelta", u"return"],
[u"y", u"and"],
[u"ya que", u"since"],
[u"ya", u"already"],
[u"yo", u"I"],
[u"zona", u"zone"]]
