#!/usr/bin/env python
# -*- coding: latin-1 -*- 
words = [["a partir de", "from, as of"],
["a través de", "through, across"],
["a", "a, to"],
["abajo", "down, below, downstairs"],
["abandonar", "to abandon"],
["abrir", "to open, unlock"],
["absoluto/a", "absolute"],
["abuelo", "grandfathers, grandpa"],
["acabar", "to finish"],
["acaso", "perhaps, maybe"],
["acción\ciones", "action"],
["aceptar", "to accept"],
["acercar", "to approach"],
["acompañar", "to accompany"],
["acordar", "to decide"],
["actitud", "attitude"],
["actividad", "activity"],
["acto", "act"],
["actual", "present"],
["actuar", "to act"],
["acudir", "to go, come"],
["acuerdo", "agreement"],
["adelante", "ahead"],
["además de", "in addition to, besides, furthermore"],
["además", "in addition, besides, furthermore"],
["adquirir", "to acquire"],
["advertir", "to notice, warn"],
["afectar", "to affect"],
["afirmar", "to affirm"],
["agua", "water"],
["ahí", "there"],
["ahí", "there"],
["ahora", "now"],
["aire", "air"],
["al", "to, to the"],
["alcanzar", "to reach"],
["alejar", "to move away, remove"],
["alemán/mana", "german"],
["algo", "something"],
["alguien", "somebody, someone"],
["alguien", "somebody"],
["algún", "some, any"],
["alguno/a", "some, any"],
["allá", "there"],
["allí", "there"],
["alma", "soul"],
["alto/a", "tall, high, stop"],
["altura", "height"],
["amar", "to love"],
["ambos/bas", "both"],
["americano/a", "american"],
["amigo/a", "friend"],
["amor", "love"],
["amplio/plia", "ample"],
["añadir", "to add"],
["análisis", "analysis"],
["andar", "to walk"],
["animal", "animal"],
["año", "year"],
["ante", "before, in front of"],
["ante", "before"],
["anterior", "previous"],
["antes de", "before"],
["antiguo/gua", "ancient, old"],
["anunciar", "to announce"],
["aparecer", "to appear"],
["apenas", "hardly,scarcely"],
["aplicar", "to apply"],
["apoyar", "to support, lean"],
["aprender", "to learn"],
["aprovechar", "to take advantage of"],
["aquel", "that"],
["aquello/a", "that"],
["aquí", "here"],
["árbol", "tree"],
["arma", "weapon"],
["arriba", "up"],
["arte", "art"],
["asegurar", "to assure"],
["así como", "as well as, such, like that"],
["así que", "so, therefore"],
["así", "like this"],
["aspecto", "aspect"],
["asunto", "matter, bussiness"],
["atención\ciones", "attention"],
["atrás", "back, behind"],
["atreverse", "to dare"],
["aumentar", "to increase, raise"],
["aun", "even"],
["aún", "still"],
["aunque", "though, although"],
["auténtico/a", "authentic"],
["autor/a", "author"],
["autoridad", "authority"],
["avanzar", "to advance"],
["ayer", "yesterday"],
["ayuda", "aid, help"],
["ayudar", "to help"],
["azul", "blue"],
["bajar", "to bring down, lower, go down"],
["bajo/a", "low, short, faint"],
["barcelona", "barcelona"],
["barrio", "neighborhood"],
["base", "base, basis"],
["bastante", "fairly, rather"],
["bastar", "to be enough, suffice"],
["beber", "to drink"],
["bien", "well, good"],
["blanco/a", "white"],
["boca", "mouth"],
["brazo", "arm"],
["buen", "good, well"],
["buscar", "to look for, to seek"],
["caballo", "horse"],
["caber", "to fit, go into"],
["cabeza", "head"],
["cabo", "end, stub"],
["cada", "each"],
["cadena", "chain"],
["caer", "to fall"],
["calle", "street"],
["cama", "bed"],
["cambiar", "to change"],
["cambio", "change"],
["caminar", "to walk"],
["camino", "road"],
["campaña", "countryside"],
["campo", "field"],
["cantar", "to sing"],
["cantidad", "quantity"],
["capacidad", "capacity"],
["capaz\paces", "able"],
["capital", "capital"],
["cara", "face"],
["carácter/racteres", "character"],
["carne", "meat"],
["carrera", "running"],
["carta", "letter"],
["casa", "house"],
["casar", "to marry"],
["casi", "almost"],
["caso", "case"],
["catalán", "catalan"],
["causa", "cause, reason"],
["celebrar", "to celebrate"],
["célula", "cell"],
["central", "central"],
["centro", "center, downtown"],
["cerebro", "brain"],
["cerrar", "to close"],
["chica", "small, girl,litlle"],
["chico/a", "boy, girl"],
["cielo", "sky, heaven"],
["ciencia", "science"],
["científico/a", "scientific"],
["ciento", "one hundred"],
["cierto/a", "TRUE"],
["cinco", "five"],
["cine", "cinema, movies"],
["circunstancia", "circumstance"],
["ciudad", "city"],
["ciudadano/a", "citizen"],
["civil", "civil"],
["claro/a", "clearly, clear"],
["clase", "class"],
["coche", "car, automobile, coach, carriage"],
["coger", "to take"],
["colocar", "to place, put"],
["color", "color"],
["comentar", "to comment, discuss, mention"],
["comenzar", "to begin, start"],
["comer", "to eat"],
["como", "as, since, like"],
["cómo", "how"],
["compañero/a", "partner, companion"],
["compañía", "company"],
["completo", "complete, full"],
["comprar", "to buy, purchase"],
["comprender", "to comprehend, to understand"],
["comprobar", "to check"],
["común\munes", "common"],
["comunicación\ciones", "communication"],
["con que", "so long as"],
["con", "with"],
["concepto", "concept"],
["conciencia", "conscience"],
["concreto", "concrete, specific"],
["condición\siones", "condition"],
["conducir", "to drive"],
["conjunto", "joint, outfit, band"],
["conocer", "to know, meet"],
["conocimiento", "knowlogde"],
["consecuencia", "consequence"],
["conseguir", "to obtain"],
["conservar", "to conserve"],
["considerar", "to consider"],
["consistir", "to consist"],
["constante", "constant"],
["constituir", "to constitute"],
["construir", "to construct, build"],
["contacto", "contact"],
["contar", "to count"],
["contemplar", "to contemplate"],
["contener", "to contain"],
["contestar", "to answer, reply"],
["continuar", "to continue"],
["contra", "against"],
["contrario", "opposite"],
["control", "control, check"],
["controlar", "to control"],
["convencer", "to convince"],
["conversación", "conversation"],
["convertir", "to turn into, convert"],
["corazón", "heart"],
["correr", "to run, race"],
["corresponder", "to correspond, belong"],
["corriente", "current"],
["cortar", "to cut"],
["cosa", "thing"],
["costumbre", "custom, habit"],
["crear", "to create"],
["crecer", "to grow, increase"],
["creer", "to believe"],
["crisis", "crisis"],
["cruzar", "to cross"],
["cuadro", "picture, square, painting"],
["cual", "as, like"],
["cuál", "which, what"],
["cualquier", "any"],
["cuando", "when"],
["cuanto", "how much, as"],
["cuánto", "how much"],
["cuarto/a", "quarter"],
["cuatro", "four"],
["cubrir", "to cover"],
["cuenta", "count"],
["cuerpo", "body"],
["cuestión", "matter, affair"],
["cultura", "culture"],
["cultural", "cultural"],
["cumplir", "to accomplish, carry out"],
["cuyo/a", "whose, of whom"],
["dar", "to give"],
["dato", "data"],
["de", "of, from"],
["deber", "to owe"],
["decidir", "to decide"],
["decir", "to say, tell"],
["decisión", "decision"],
["declarar", "to declare"],
["dedicar", "to dedicate"],
["dedo", "finger, toe"],
["defender", "to defend"],
["defensa", "defense"],
["definir", "to define"],
["definitivo", "definitive"],
["dejar", "to leave"],
["del", "of, from"],
["demás", "rest of the"],
["demasiado", "too much"],
["democracia", "democracy"],
["demostrar", "to demonstrate"],
["dentro de", "within, in"],
["depender", "to depend"],
["derecha", "right"],
["derecho", "straight, rigth"],
["desaparecer", "to disappear"],
["desarrollar", "to develop"],
["desarrollo", "development"],
["desconocer", "to not know, fail to recognize"],
["descubrir", "to discover"],
["desde que", "since"],
["desde", "from, since"],
["desear", "to wish"],
["deseo", "desire"],
["despertar", "to wake up"],
["después de", "after"],
["después", "afterwards, then"],
["destino", "destiny, destination"],
["detener", "to stop"],
["determinar", "to determine"],
["día", "day"],
["diario/ria", "newspaper"],
["diez", "ten"],
["diferencia", "difference"],
["diferente", "different"],
["difícil", "difficult"],
["dificultad", "difficulty"],
["dinero", "money"],
["dios/diosa", "god, goddes"],
["dirección", "address, direction"],
["directo", "direct, straight"],
["director/tora", "director, manager"],
["dirigir", "to direct"],
["disponer", "to arrange"],
["distancia", "distance"],
["distinto", "different"],
["diverso", "diverse"],
["doble", "double"],
["doctor/tora", "doctor"],
["dolor", "pain"],
["don", "gift, talent"],
["donde", "where"],
["dónde", "where"],
["dormir", "to sleep"],
["dos", "two"],
["duda", "doubt"],
["durante", "during"],
["duro", "hard"],
["e", "and"],
["echar", "to throw, cast"],
["económico", "economic, economical"],
["edad", "age"],
["efecto", "efect"],
["ejemplo", "example"],
["ejército", "army"],
["ejército", "army"],
["el/a", "the"],
["él", "he, him"],
["elección", "election"],
["elegir", "to choose, select"],
["elemento", "element"],
["elevar", "to elevate, raise"],
["empezar", "to begin, start"],
["empresa", "company"],
["en", "in, into, inside, on"],
["encender", "to light, switch on, set fire to"],
["encima", "on top"],
["encontrar", "to find"],
["encuentro", "encounter, meeting"],
["energía", "energy"],
["enfermedad", "illness, disease, sickness"],
["enfermo", "ill, sick"],
["enorme", "enormous"],
["enseñar", "to teach"],
["entender", "to understand"],
["enterar", "to find out, inform"],
["entonces", "then"],
["entrada", "entrance, entry"],
["entrar", "to enter"],
["entre", "between, among"],
["entregar", "to deliver, give"],
["enviar", "to send"],
["época", "epoch, period"],
["equipo", "equipment, team"],
["error", "error, mistake"],
["es decir", "that is to say"],
["escapar", "to escape, run away"],
["escribir", "to write"],
["escritor/tora", "writer"],
["escuchar", "to listen, heard"],
["ese/a", "that"],
["esfuerzo", "effort, endeavor, exertion"],
["eso", "that"],
["espacio", "space"],
["espalda", "back"],
["españa", "spain"],
["español/ñola", "spanish"],
["española", "Spanish, spaniard"],
["especial", "special"],
["especie", "species"],
["esperanza", "hope, prospect"],
["esperar", "to hope, wait"],
["espíritu", "spirit"],
["ésta", "is"],
["establecer", "to establish"],
["estado", "state"],
["estados unidos", "united States"],
["estar", "to be, stay"],
["éste/a", "this one"],
["este/a", "this"],
["este", "this"],
["esto", "this"],
["estrella", "star"],
["estructura", "structure"],
["estudiar", "to study"],
["estudio", "study, studio"],
["etapa", "stage"],
["europa", "europe"],
["europeo/pea", "european"],
["evidente", "evident"],
["evitar", "to avoid"],
["exacto/a", "exact"],
["exigir", "to demand"],
["existencia", "existence"],
["existir", "to exist"],
["éxito", "success"],
["experiencia", "experience"],
["explicar", "to explain"],
["expresión", "expression"],
["extender", "to extend"],
["exterior", "outside, exterior"],
["extranjero/a", "foreigner, foreign"],
["extraño", "strange, foreign"],
["extremo", "extreme"],
["fácil", "easy"],
["falta", "lack"],
["faltar", "to lack"],
["familia", "family"],
["familiar", "familial, family"],
["famoso", "famous"],
["fenómeno", "phenomenon"],
["fiesta", "celebration, party"],
["figura", "figure, shape"],
["figura", "to figure"],
["fijar", "to faten, affix"],
["fin", "end"],
["final", "end, final"],
["físico", "physical, physicist"],
["flor", "flower"],
["fondo", "bottom, rear"],
["forma", "shape"],
["formar", "to form"],
["francés/cesa", "french"],
["francés", "french"],
["francia", "france"],
["frase", "phrase"],
["frecuencia", "frequency"],
["frente", "in front"],
["frío/a", "cold, cool"],
["fuego", "fire"],
["fuente", "source"],
["fuera de", "outside of, beyond"],
["fuerte", "hard, strong"],
["fuerza", "force, strength"],
["función", "function"],
["funcionar", "to work, run, function"],
["fundamental", "fundamental"],
["fútbol", "soccer, football"],
["futuro", "future"],
["ganar", "to win"],
["general", "general"],
["gente", "people"],
["gesto", "gesture"],
["gobierno", "government"],
["golpe", "blow"],
["gracia", "grace"],
["gran", "big"],
["grande", "big, great"],
["grave", "grave, deep"],
["gritar", "to shout, scream"],
["grupo", "group"],
["guardar", "to keep"],
["guerra", "war"],
["gustar", "to taste, like"],
["gusto", "taste, pleasure, liking"],
["haber", "to have, has"],
["habitación", "room, bedroom"],
["habitual", "habitual, usual"],
["hablar", "to speak, talk"],
["hacer", "to do, make"],
["hacia", "towards"],
["hallar", "to find, discover"],
["hasta que", "until, even"],
["hasta", "until, even"],
["hecho/cha", "fact"],
["hermana", "sister"],
["hermano/a", "brother"],
["hermoso/a", "beautiful"],
["hija", "daughter"],
["hijo/a", "son, daughter"],
["historia", "history"],
["histórico", "historical"],
["hombre", "man"],
["hombro", "shoulder"],
["hora", "hour"],
["hoy", "today"],
["humano/a", "human"],
["idea", "idea"],
["iglesia", "church"],
["igual", "equal"],
["imagen\imágenes", "image"],
["imaginar", "to imagine"],
["impedir", "to prevent"],
["imponer", "to impose, command"],
["importancia", "importance"],
["importante", "important"],
["importar", "to matter, be important"],
["imposible", "impossible"],
["incluir", "to include"],
["incluso", "even, in fact"],
["indicar", "to indicate"],
["individuo", "individual"],
["información\ciones", "information"],
["informar", "to inform"],
["informar", "to inform"],
["inglés/glesa", "english"],
["iniciar", "to initiate"],
["inmediato/a", "immediate"],
["insistir", "to insist"],
["instante", "moment, instant"],
["intentar", "to try"],
["interés\reses", "interest"],
["interesar", "to interest"],
["interior", "interior, inner"],
["internacional", "international"],
["introducir", "to introduce, insert"],
["ir", "to go"],
["izquierda", "left"],
["jamás", "never"],
["jefe/a", "chief, leader, boss"],
["joven", "young person"],
["juego", "game, playing"],
["jugador", "player, gambler"],
["jugar", "to play, gambler"],
["juicio", "judgment, sense"],
["junto a", "next to"],
["junto", "together, joined, close"],
["justo", "just, fair"],
["labio", "lip"],
["lado", "side"],
["lanzar", "to throw"],
["largo", "long"],
["lector/tora", "reader"],
["leer", "to read"],
["lengua", "language, tongue"],
["lenguaje", "language"],
["lento", "slow"],
["levantar", "to lift, raise"],
["ley", "law"],
["libertad", "freedom"],
["libre", "free"],
["libro", "book"],
["limitar", "to limit"],
["línea", "line"],
["literatura", "literature"],
["llamar", "to call, phone"],
["llegar", "to arrive, come"],
["llenar", "to fill"],
["lleno", "full"],
["llevar", "to take, carry"],
["llorar", "to cry, weep"],
["lo", "the for it"],
["loco/a", "crazy, insane"],
["lograr", "to obtain, achieve, get"],
["lucha", "fight, struggle"],
["luego", "then, later"],
["lugar", "place"],
["luz", "light, lighting"],
["madre", "mother"],
["mal", "badly, poorly, incorrectly"],
["malo/a", "bad"],
["mañana", "tomorrow"],
["mandar", "to command"],
["manera", "way, manner"],
["manifestar", "to declare"],
["mano", "hand"],
["mantener", "to maintain"],
["máquina", "machine"],
["mar", "sea"],
["marcar", "to mark"],
["marcha", "march"],
["marchar", "to march"],
["marido", "husband"],
["mas", "but"],
["más", "more"],
["masa", "mass"],
["matar", "to kill"],
["materia", "matter"],
["material", "material"],
["máximo", "maximum"],
["mayor", "greater"],
["mayoría", "majority"],
["mediante", "by means of"],
["médico/a", "doctor"],
["medida", "measurement"],
["medio/dia", "means"],
["mejor", "better"],
["memoria", "memory"],
["menor", "minor"],
["menos", "less"],
["menudo", "small, insignificant"],
["mercado", "market"],
["merecer", "to deserve"],
["mes", "month"],
["mesa", "it pulls"],
["meter", "to put"],
["método", "method"],
["metro", "meter"],
["mi\mis", "my, not me"],
["mí", "me, not my"],
["miedo", "fear"],
["miembro", "member"],
["mientras que", "whereas, while"],
["mientras", "while"],
["mil", "thousand"],
["militar", "military man"],
["millón", "million"],
["mínimo/a", "minimum"],
["ministro/tra", "minister"],
["minuto", "minute"],
["mío/a", "mine"],
["mirada", "watched"],
["mirar", "to watch"],
["mismo", "same"],
["mitad", "half"],
["modelo", "model"],
["moderno/a", "modern"],
["modo", "way, manner, mode"],
["momento", "moment"],
["moral", "moral"],
["morir", "to die"],
["mostrar", "to show"],
["motivo", "reason"],
["mover", "to move, stir"],
["movimiento", "movement, motion"],
["muchacho/cha", "boy"],
["mucho", "much"],
["muerte", "death"],
["mujer/jeres", "woman, women"],
["mundial", "worldwide"],
["mundo", "world"],
["música", "music"],
["muy", "very, highly"],
["nacer", "to be born"],
["nacional", "national"],
["nada", "nothing"],
["nadie", "nobody, no-one"],
["natural", "natural"],
["naturaleza", "nature"],
["necesario/ria", "necessary"],
["necesidad", "necessity,need"],
["necesitar", "to need"],
["negar", "to deny"],
["negocio", "business"],
["negro/gra", "black"],
["ni siquiera", "not even"],
["ni", "nor, neither"],
["niña", "girl, child"],
["ningún", "none"],
["ninguno/a", "no, none, nobody, no one"],
["niño/a", "boy, girl"],
["nivel", "level"],
["no", "no"],
["noche", "night"],
["nombre", "name"],
["normal", "normal"],
["norteamericano/a", "North American"],
["notar", "to notice"],
["noticia", "the news"],
["novela", "novel"],
["nuestro/tra", "ours"],
["nuevo/a", "new"],
["número", "number"],
["nunca", "never"],
["o", "or"],
["objetivo", "objective"],
["objeto", "object"],
["obligar", "to force, oblige"],
["obra", "work"],
["observar", "to observe"],
["obtener", "to obtain, get"],
["ocasión\siones", "occasion"],
["ocho", "eight"],
["ocupar", "to occupy"],
["ocurrir", "to happen"],
["oficial", "official"],
["ofrecer", "to offer"],
["oír", "to hear"],
["ojo", "eye"],
["olvidar", "to forget"],
["operación", "operation"],
["opinión", "opinion"],
["origen/rígenes", "origin"],
["oro", "gold"],
["oscuro/a", "dark, obscure"],
["otro/tra", "another, other"],
["paciente", "patient"],
["padre", "father"],
["pagar", "to pay"],
["página", "page"],
["país", "country, nation"],
["países", "countries"],
["palabra", "word"],
["papel", "paper"],
["par", "pair, couple"],
["para que", "so that"],
["para", "for, towars, stop"],
["parar", "to stop, stand"],
["parecer", "to seem"],
["pared", "wall"],
["pareja", "even, couple, pair"],
["parte", "part"],
["participar", "to participate"],
["particular", "particular, private"],
["partido", "party, game"],
["partir", "to start off, depart, slipt, divide"],
["pasado", "past"],
["pasar", "to happen, pass"],
["paso", "step"],
["paso", "step"],
["paz", "peace"],
["pecho", "chest"],
["pedir", "to request, ask for"],
["película", "film, movie"],
["peligro", "danger"],
["pelo", "hair"],
["pena", "pain, penalty"],
["pensamiento", "though"],
["pensar", "to think"],
["peor", "worse"],
["pequeño/a", "small"],
["perder", "to lose, miss"],
["perfecto", "perfect"],
["periódico/a", "newspaper"],
["periodista", "journalist"],
["permanecer", "to remain"],
["permitir", "to allow"],
["pero", "but"],
["perro/rra", "dog"],
["persona", "person"],
["personaje", "person"],
["personal", "personal"],
["pertenecer", "to belong to"],
["pesar", "to weigh"],
["peso", "weight"],
["pie", "foot"],
["piedra", "stone"],
["piel", "skin"],
["pierna", "leg"],
["piso", "floor"],
["placer", "to please"],
["plan", "plan"],
["plantear", "to expound, raise"],
["plaza", "seat, square"],
["pleno", "full, complete"],
["población\ciones", "population"],
["pobre", "poor"],
["poco/a", "little, few"],
["poder", "to be able to, can, might, may"],
["policía", "police"],
["política", "politics"],
["político", "political"],
["poner", "to put"],
["por ejemplo", "for example"],
["por", "by, for, per"],
["porque", "because, why"],
["poseer", "to posses, own"],
["posibilidad", "possibility"],
["posible", "posible"],
["posición\ciones", "position"],
["práctico", "practical"],
["precio", "price, cost"],
["preciso/a", "precise"],
["preferir", "to prefer"],
["pregunta", "a question"],
["preguntar", "to ask"],
["prensa", "press"],
["preocupar", "to worry"],
["preparar", "to prepare"],
["presencia", "presence"],
["presentar", "to present"],
["presente", "present"],
["presidente", "president"],
["pretender", "to try, court"],
["primer", "first"],
["primero/a", "first"],
["principal", "principal"],
["principio", "beginning, principle"],
["privar", "deprive"],
["probable", "probable"],
["problema", "problem"],
["proceso", "process"],
["producir", "to produce"],
["producto", "product"],
["profesional", "professional"],
["profesor/sora", "professor, teacher"],
["profundo/a", "deep"],
["programa", "program"],
["pronto/a", "soon, quick, prompt"],
["propio/pia", "own"],
["proponer", "to propose, nominate"],
["provocar", "to cause"],
["próximo/a", "next"],
["proyecto", "project"],
["prueba", "test, proof, evidence"],
["publicar", "to publish"],
["público/a", "public"],
["pueblo", "town"],
["pueblo", "town"],
["puerta", "door"],
["pues", "then, since, because"],
["puesto", "position, place"],
["punto", "point"],
["puro/a", "pure"],
["que", "that"],
["qué", "what"],
["quedar", "to stay"],
["querer", "to want"],
["quien", "who"],
["quién", "who"],
["quitar", "to remove, take away"],
["quizá", "perhaps, maybe"],
["radio", "radio"],
["rápido/a", "rapid, quick"],
["rato", "short while"],
["razón\zones", "reason"],
["real", "royal, real"],
["realidad", "reality"],
["realizar", "to make, realize"],
["recibir", "to receive"],
["reciente", "recent"],
["recoger", "to gather, pick up"],
["reconocer", "to recognize"],
["recordar", "to remember, remind"],
["recorrer", "to cross, travel through"],
["recuerdo", "memory, remembrance"],
["recuperar", "to recover"],
["reducir", "to reduce"],
["referir", "to refer"],
["régimen", "regime"],
["regresar", "to return, come back"],
["reír", "to laugh"],
["relación\ciones", "relation"],
["religioso/a", "religious"],
["repetir", "to repeat"],
["representar", "to represent"],
["resolver", "to solve"],
["responder", "to answer"],
["responsable", "responsible"],
["respuesta", "answer"],
["resto", "rest"],
["resultado", "result, outcome"],
["resultar", "to turn out, work out, succeed"],
["reunión\niones", "meeting"],
["reunir", "to unite, join"],
["revista", "magazine"],
["rey", "king"],
["rico/a", "rich"],
["riesgo", "risk"],
["río", "river"],
["rodear", "to surround, encircle"],
["rojo/a", "red"],
["romper", "to break"],
["ropa", "clothes"],
["rostro", "face"],
["saber", "to know"],
["sacar", "to remove, take out"],
["sala", "room, living room"],
["salida", "exit, departure"],
["salir", "to leave, go out"],
["sangre", "blood"],
["secreto/a", "secret"],
["sector", "sector"],
["seguir", "to follow"],
["según", "according to"],
["segundo", "second"],
["seguridad", "security"],
["seguro/a", "safe"],
["seis", "six"],
["semana", "week"],
["semejante", "similar"],
["señalar", "to indicate, point out"],
["señor/ñora", "sir/madam"],
["sensación\ciones", "sensation, feeling"],
["sentar", "to seat, sit"],
["sentido/a", "heartfelt,sense"],
["sentimiento", "feeling"],
["sentimiento", "feeling"],
["sentir", "to feel"],
["separar", "to separate"],
["ser", "to be"],
["serie/ria", "series"],
["serio", "serious"],
["servicio", "service"],
["servir", "to serve"],
["sexo", "sex"],
["sexual", "sexual"],
["si", "if, yes"],
["sí", "yes"],
["sido", "been"],
["siempre", "always"],
["siete", "seven"],
["siglo", "century"],
["significar", "to mean"],
["siguiente", "following, next"],
["silencio", "silence"],
["simple", "simple"],
["sin", "without"],
["sino que", "but that"],
["sino", "but, rather"],
["sistema", "system"],
["sitio", "place, site"],
["situación\ciones", "situation"],
["situar", "to locate"],
["sobre", "envelope, on"],
["social", "social"],
["socialista", "socialist"],
["sociedad", "society"],
["sol", "sun"],
["solo/a", "alone"],
["sólo", "only"],
["solución\ciones", "solution"],
["sombra", "shadow"],
["someter", "to subjugate"],
["sonar", "to sound"],
["sonreír", "to smile"],
["sonrisa", "smile"],
["sorprender", "to surprise"],
["sostener", "to maintain, support, hold"],
["su", "his"],
["subir", "to raise"],
["suceder", "to happen/ occur"],
["suelo", "ground, floor"],
["sueño", "dream"],
["suerte", "luck"],
["suficiente", "enough"],
["sufrir", "to suffer"],
["superar", "to surpass"],
["superior", "superior"],
["suponer", "to suppose"],
["surgir", "to arise"],
["suyo/a", "his/her/its"],
["tal vez", "perhaps"],
["tal", "so"],
["también", "also, too"],
["tampoco", "neither"],
["tan", "so"],
["tanto/a", "so much"],
["tarde", "late"],
["tarea", "homewrok"],
["técnica", "technique"],
["técnico/a", "technician"],
["televisión\siones", "television"],
["tema", "theme"],
["temer", "to fear"],
["tender", "to strech out"],
["tener", "to have"],
["teoría", "theory"],
["tercer", "third"],
["terminar", "to finish"],
["término", "term"],
["texto", "text"],
["tía", "aunt"],
["tiempo", "time"],
["tierra", "earth"],
["tío/tía", "uncle / aunt"],
["tipo/a", "guy"],
["tirar", "to throw"],
["título", "title"],
["tocar", "to touch"],
["todavía", "still"],
["todo/a", "everything"],
["tomar", "to take, to drink"],
["tono", "tone"],
["total", "total"],
["trabajar", "to work"],
["trabajo", "job"],
["traer", "to bring"],
["tras", "after"],
["tratar", "to try"],
["tres", "three"],
["tu", "your, you"],
["último/a", "last"],
["un/una", "a, an"],
["único/a", "only"],
["único", "only, unique"],
["unidad", "unit"],
["unir", "to unite"],
["uno/una", "one"],
["usar", "to use"],
["uso", "use"],
["usted", "you"],
["utilizar", "to use"],
["vacío/cía", "empty"],
["valer", "to be worth"],
["valor", "value"],
["varias", "several"],
["varios", "several"],
["vecino/a", "neighbor"],
["veinte", "twenty"],
["velocidad", "speed"],
["vender", "to sell"],
["venir", "to come"],
["ventana", "window"],
["ver", "to see"],
["verano", "summer"],
["verdad", "truth"],
["verdadero/a", "TRUE"],
["verde", "green"],
["vestir", "to dress"],
["vez\veces", "time"],
["viaje", "travel"],
["vida", "life"],
["viejo/a", "old"],
["viento", "wind"],
["violencia", "violence"],
["vista", "vision"],
["vivir", "to live"],
["vivo/a", "alive"],
["voluntad", "will"],
["volver", "to return"],
["voz\voces", "voice"],
["vuelta", "return"],
["y", "and"],
["ya que", "since"],
["ya", "already"],
["yo", "I"],
["zona", "zone"]]
