name = "S - Draws Hashmarks" 
description = "Random vertical lines on horizontal lines"
knob1 = "Number of Horizontal Lines"
knob2 = "Line Width"
knob3 = "Number of Vertical Lines" 
knob4 = "Color"
released = "March 21 2017"
