name = "S - Grid Random Polygons - Filled" 
description = "Grid of filled polygons with random shapes"
knob1 = "X Offset"
knob2 = "Y Offset"
knob3 = "Size" 
knob4 = "Color"
released = "March 21 2017"
