name = "S - Connected Scope" 
description = "Line oscilloscope with circles and random bits"
knob1 = "Line Width"
knob2 = "Circle Diameter"
knob3 = "Random Bits Amount" 
knob4 = "Color"
released = "March 21 2017"
